services:
  mysql:
    image: mysql:latest
    container_name: fastapi_crud_mysql_db
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: mlops_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:


